version: '3.3'
services:
  vaccinstatus_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    restart: always
    container_name: vaccinstatus_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
  app:
    image: andreassundstrom/vaccinstatus:1.0
    restart: always
    environment:
      ConnectionStrings__VaccinStatus: "Server=vaccinstatus_db;User ID=SA;Password=yourStrong(!)Password;Database=VaccinStatus;"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "80:8080"
    depends_on:
      - vaccinstatus_db
